-- Create Table for Dictionary
CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR(5) NOT NULL UNIQUE
);

-- Create Table for High Scores
CREATE TABLE IF NOT EXISTS high_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    score INTEGER NOT NULL,
    achieved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed Data (Valid 5-Letter Indonesian Words)
INSERT OR IGNORE INTO words (word) VALUES ('ABADI');
INSERT OR IGNORE INTO words (word) VALUES ('ACARA');
INSERT OR IGNORE INTO words (word) VALUES ('AGAMA');
INSERT OR IGNORE INTO words (word) VALUES ('AKHIR');
INSERT OR IGNORE INTO words (word) VALUES ('AKSES');
INSERT OR IGNORE INTO words (word) VALUES ('AKTIF');
INSERT OR IGNORE INTO words (word) VALUES ('AKTOR');
INSERT OR IGNORE INTO words (word) VALUES ('ALAMI');
INSERT OR IGNORE INTO words (word) VALUES ('ALBUM');
INSERT OR IGNORE INTO words (word) VALUES ('AMBIL');
INSERT OR IGNORE INTO words (word) VALUES ('AMPUH');
INSERT OR IGNORE INTO words (word) VALUES ('ANDAI');
INSERT OR IGNORE INTO words (word) VALUES ('ANEKA');
INSERT OR IGNORE INTO words (word) VALUES ('ANGIN');
INSERT OR IGNORE INTO words (word) VALUES ('ANGKA');
INSERT OR IGNORE INTO words (word) VALUES ('ANTIK');
INSERT OR IGNORE INTO words (word) VALUES ('ARENA');
INSERT OR IGNORE INTO words (word) VALUES ('ARSIP');
INSERT OR IGNORE INTO words (word) VALUES ('ASING');
INSERT OR IGNORE INTO words (word) VALUES ('BADAN');
INSERT OR IGNORE INTO words (word) VALUES ('BADUT');
INSERT OR IGNORE INTO words (word) VALUES ('BAGAI');
INSERT OR IGNORE INTO words (word) VALUES ('BAGUS');
INSERT OR IGNORE INTO words (word) VALUES ('BAHAN');
INSERT OR IGNORE INTO words (word) VALUES ('BAKAR');
INSERT OR IGNORE INTO words (word) VALUES ('BAKSO');
INSERT OR IGNORE INTO words (word) VALUES ('BALAP');
INSERT OR IGNORE INTO words (word) VALUES ('BALON');
INSERT OR IGNORE INTO words (word) VALUES ('BANTU');
INSERT OR IGNORE INTO words (word) VALUES ('BARAT');
INSERT OR IGNORE INTO words (word) VALUES ('BARIS');
INSERT OR IGNORE INTO words (word) VALUES ('BASAH');
INSERT OR IGNORE INTO words (word) VALUES ('BASUH');
INSERT OR IGNORE INTO words (word) VALUES ('BATAK');
INSERT OR IGNORE INTO words (word) VALUES ('BATAL');
INSERT OR IGNORE INTO words (word) VALUES ('BATAS');
INSERT OR IGNORE INTO words (word) VALUES ('BATIK');
INSERT OR IGNORE INTO words (word) VALUES ('BATUK');
INSERT OR IGNORE INTO words (word) VALUES ('BAWAH');
INSERT OR IGNORE INTO words (word) VALUES ('BAYAR');
INSERT OR IGNORE INTO words (word) VALUES ('BEBAS');
INSERT OR IGNORE INTO words (word) VALUES ('BEBEK');
INSERT OR IGNORE INTO words (word) VALUES ('BEDAK');
INSERT OR IGNORE INTO words (word) VALUES ('BEKAS');
INSERT OR IGNORE INTO words (word) VALUES ('BELUM');
INSERT OR IGNORE INTO words (word) VALUES ('BENAR');
INSERT OR IGNORE INTO words (word) VALUES ('BENCI');
INSERT OR IGNORE INTO words (word) VALUES ('BENDA');
INSERT OR IGNORE INTO words (word) VALUES ('BENIH');
INSERT OR IGNORE INTO words (word) VALUES ('BERAS');
INSERT OR IGNORE INTO words (word) VALUES ('BERAT');
INSERT OR IGNORE INTO words (word) VALUES ('BESAR');
INSERT OR IGNORE INTO words (word) VALUES ('BESOK');
INSERT OR IGNORE INTO words (word) VALUES ('BETON');
INSERT OR IGNORE INTO words (word) VALUES ('BIAYA');
INSERT OR IGNORE INTO words (word) VALUES ('BIBIR');
INSERT OR IGNORE INTO words (word) VALUES ('BIJAK');
INSERT OR IGNORE INTO words (word) VALUES ('BIKIN');
INSERT OR IGNORE INTO words (word) VALUES ('BILAS');
INSERT OR IGNORE INTO words (word) VALUES ('BINAR');
INSERT OR IGNORE INTO words (word) VALUES ('BIOLA');
INSERT OR IGNORE INTO words (word) VALUES ('BISIK');
INSERT OR IGNORE INTO words (word) VALUES ('BISUL');
INSERT OR IGNORE INTO words (word) VALUES ('BOCOR');
INSERT OR IGNORE INTO words (word) VALUES ('BODOH');
INSERT OR IGNORE INTO words (word) VALUES ('BOLEH');
INSERT OR IGNORE INTO words (word) VALUES ('BOSAN');
INSERT OR IGNORE INTO words (word) VALUES ('BOTOL');
INSERT OR IGNORE INTO words (word) VALUES ('BUAYA');
INSERT OR IGNORE INTO words (word) VALUES ('BUBAR');
INSERT OR IGNORE INTO words (word) VALUES ('BUBUR');
INSERT OR IGNORE INTO words (word) VALUES ('BUDAK');
INSERT OR IGNORE INTO words (word) VALUES ('BUGAR');
INSERT OR IGNORE INTO words (word) VALUES ('BUKIT');
INSERT OR IGNORE INTO words (word) VALUES ('BUKTI');
INSERT OR IGNORE INTO words (word) VALUES ('BULAN');
INSERT OR IGNORE INTO words (word) VALUES ('BULAT');
INSERT OR IGNORE INTO words (word) VALUES ('BUMBU');
INSERT OR IGNORE INTO words (word) VALUES ('JALAN');
INSERT OR IGNORE INTO words (word) VALUES ('MAKAN');
INSERT OR IGNORE INTO words (word) VALUES ('MINUM');
INSERT OR IGNORE INTO words (word) VALUES ('TIDUR');
INSERT OR IGNORE INTO words (word) VALUES ('RUMAH');
INSERT OR IGNORE INTO words (word) VALUES ('KURSI');
INSERT OR IGNORE INTO words (word) VALUES ('LAMPU');
INSERT OR IGNORE INTO words (word) VALUES ('PINTU');
INSERT OR IGNORE INTO words (word) VALUES ('KASUR');
INSERT OR IGNORE INTO words (word) VALUES ('MOTOR');
INSERT OR IGNORE INTO words (word) VALUES ('MOBIL');
INSERT OR IGNORE INTO words (word) VALUES ('HUJAN');
INSERT OR IGNORE INTO words (word) VALUES ('PANAS');
INSERT OR IGNORE INTO words (word) VALUES ('BADAI');
INSERT OR IGNORE INTO words (word) VALUES ('SIANG');
INSERT OR IGNORE INTO words (word) VALUES ('MALAM');
INSERT OR IGNORE INTO words (word) VALUES ('MERAH');
INSERT OR IGNORE INTO words (word) VALUES ('PUTIH');
INSERT OR IGNORE INTO words (word) VALUES ('HITAM');
INSERT OR IGNORE INTO words (word) VALUES ('HIJAU');
INSERT OR IGNORE INTO words (word) VALUES ('DAPUR');
INSERT OR IGNORE INTO words (word) VALUES ('KAMAR');
INSERT OR IGNORE INTO words (word) VALUES ('PAGAR');
INSERT OR IGNORE INTO words (word) VALUES ('PAPAN');
INSERT OR IGNORE INTO words (word) VALUES ('GELAS');
INSERT OR IGNORE INTO words (word) VALUES ('GARPU');
INSERT OR IGNORE INTO words (word) VALUES ('PISAU');
INSERT OR IGNORE INTO words (word) VALUES ('EMBER');
INSERT OR IGNORE INTO words (word) VALUES ('SABUN');
INSERT OR IGNORE INTO words (word) VALUES ('SIKAT');
INSERT OR IGNORE INTO words (word) VALUES ('PASTA');
INSERT OR IGNORE INTO words (word) VALUES ('GAMIS');
INSERT OR IGNORE INTO words (word) VALUES ('BALOK');
INSERT OR IGNORE INTO words (word) VALUES ('SOBEK');
INSERT OR IGNORE INTO words (word) VALUES ('KOTOR');
